### ISSUE TITLE
ModuleNotFoundError: No module named 'cmapy'

### ISSUE THREAD

**Issue by roseyunzi** [CVI-SZU/CCAM#1]
Hi,thanks for the work. But when i run`/data/yunzi/CCAM/WSOL$ OMP_NUM_THREADS=16 CUDA_VISIBLE_DEVICES=0 python train_CCAM_CUB.py --experiment CCAM_CUB_MOCO --lr 0.0001 --batch_size 16 --pretrained mocov2 --alpha 0.75`

I got a error :ModuleNotFoundError: No module named 'cmapy'
where can i import this file?

**Comment by Sierkinhane** [comment]
hello, please use pip to install the cmapy package. `pip install cmapy` .

**Comment by roseyunzi** [comment]
Oh! Thank you,sorry that i didn't try that...
