### ISSUE TITLE
The environment

### ISSUE THREAD

**Issue by rjy-fighting** [CVI-SZU/CCAM#10]
May I know the environment in which the experiment was conducted?（For example，GPU）

**Comment by Sierkinhane** [comment]
Hi, all experiments were conducted on Tesla A100 or V100.

**Comment by rjy-fighting** [comment]
> Hi, all experiments were conducted on Tesla A100 or V100. Torch == 1.7.1, Python==3.8.8.

Thank you! How mang GPUs did you use in your experiment?

**Comment by Sierkinhane** [comment]
WSOL;
          CUB-200-2011 -- a single Tesla A100
          ILSVRC (ImageNet-1K) -- 4 Tesla A100 or V100
WSSS:
          PASCAL VOC2012 -- a single Tesla A100
