### ISSUE TITLE
test loss does not decrease

### ISSUE THREAD

**Issue by mwmilad** [CVI-SZU/CCAM#12]
hi, I train your code on mocov2 and CUB Dataset but test loss does not decrease... still epoch 17

![Screenshot 2023-03-08 013126](https://user-images.githubusercontent.com/86923119/223563536-5351e7a9-bff6-4a89-96a0-fd470bf49a82.png)

**Comment by Sierkinhane** [comment]
Hi, as the losses work in an adversarial manner, the loss may not be like the normal one. You can check the generated class-agnostic activation map.
