### ISSUE TITLE
损失函数计算

### ISSUE THREAD

**Issue by xiaoyaod** [CVI-SZU/CCAM#13]
在论文中有提到怎么确定前景，但在训练计算损失时并没有在batch 中计算每张图像得到的是否是前景
感谢您提供的代码

**Comment by Sierkinhane** [comment]
你好，因为前景损失和背景损失是一样的，所以在训练的时候不需要确定前背景。并且，每张图产生的p激活的语义是一样的，都是前景或者都是背景，1-p可以得到背景或者前景区域。

**Comment by xiaoyaod** [comment]
非常感谢
