### ISSUE TITLE
Missing ckpt in the SPOL folder.

### ISSUE THREAD

**Issue by Aoran0215** [CVI-SZU/CCAM#15]
First of all, thank you for your work.

--ckpt ./ImageNet_resnet50_uns/checkpoint_localization_imagenet_resnet50_19.pth.tar  in run_ilsvrc.sh
and
 --ckpt ./CUB_resnet50_uns/checkpoint_localization_cub_resnet50_99.pth.tar  in run_cub.sh

**Comment by Sierkinhane** [comment]
Now Availabel at [here](https://drive.google.com/drive/folders/1Uoyh3XLdz5VqWvWNjxoqMfRryu1nkQTL)
