### ISSUE TITLE
How to extract the bbox of CCAM

### ISSUE THREAD

**Issue by MsterDC** [CVI-SZU/CCAM#16]
Hello, I am reproducing your work recently and trying to integrate one of my enhancement modules into your model, but now I don't know how to extract the bbox box from the trained CCAM model, can you help me solve this problem?

**Comment by Sierkinhane** [comment]
Hi, the training pipeline includes hte extraction of pseudo bbox.

**Comment by MsterDC** [comment]
Hi,&nbsp;
&nbsp; Thanks for your reply.
&nbsp; I also discovered this later, but it was too late for me to retract the email, and I closed the issue.&nbsp;
&nbsp; Thanks again for the reply!
