### ISSUE TITLE
Training annotations of ILSVRC

### ISSUE THREAD

**Issue by MsterDC** [CVI-SZU/CCAM#17]
Hello,
Would you mind providing the download links for the "train.txt" and "val.txt" of the ImageNet dataset?
I will be very grateful!

**Comment by Sierkinhane** [comment]
Here are the annotations: https://drive.google.com/drive/folders/1-YAT9SrtuDxYdmvWpTWm6uNs1dIYwKu4?usp=drive_link

**Comment by MsterDC** [comment]
Thanks a lot !
