### ISSUE TITLE
ILSVRC metadata

### ISSUE THREAD

**Issue by mnl12** [CVI-SZU/CCAM#18]
Hello,
I was wondering if you could share val.txt and train.txt for ILSVRC dataset, because I could not find it in the download link of the dataset. Thanks.

**Comment by Sierkinhane** [comment]
Hi, here are the annotations: https://drive.google.com/drive/folders/1-YAT9SrtuDxYdmvWpTWm6uNs1dIYwKu4?usp=drive_link.

Btw, welcome to star our project :)
