### ISSUE TITLE
The size of x1, x2 not match

### ISSUE THREAD

**Issue by jokingww** [CVI-SZU/CCAM#20]
I just read your paper and code, it's a great work. I'm confused in code 'model.py',
```python
    x1 = self.layer3(x)
    x2 = self.layer4(x1)
    return torch.cat([x2, x1], dim=1)
```
after downsample, the size of x2, x1 are not match. Did I understand something wrong?

**Comment by Sierkinhane** [comment]
Hi, we have changed the the last stride of resnet block. More details can be found at [here](https://github.com/CVI-SZU/CCAM/blob/78448d4654465251dfb0b30ba4d7f82af84b0919/WSSS/core/resnet.py#L90).

**Comment by jokingww** [comment]
I didn't notice this change. Thanks for explaination.
